/**
 * Paradigm reference tables for Greek noun declensions and verb conjugations.
 */

export const NOUN_PARADIGMS = [
  {
    id: '1st-eta',
    title: '1st Declension (η-type)',
    subtitle: 'Feminine nouns like ζωή, ἀρχή, γραφή',
    note: 'The η-type 1st declension is the most regular. The eta (η) runs through all singular forms. Plural forms are identical across all 1st declension subtypes.',
    headers: ['', 'Singular', 'Plural'],
    rows: [
      ['Nominative', '-η', '-αι'],
      ['Genitive', '-ης', '-ῶν'],
      ['Dative', '-ῃ', '-αῖς'],
      ['Accusative', '-ην', '-άς'],
    ],
    examples: 'ζωή → ζωή, ζωῆς, ζωῇ, ζωήν / ζωαί, ζωῶν, ζωαῖς, ζωάς',
  },
  {
    id: '1st-alpha',
    title: '1st Declension (α-type)',
    subtitle: 'Feminine nouns like δόξα, ἀλήθεια, ἐκκλησία',
    note: 'When the noun stem ends in ε, ι, or ρ, the alpha (α) is kept throughout the singular. Otherwise, α appears in nom/acc but shifts to η in gen/dat. This is called "mixed" 1st declension.',
    headers: ['', 'Pure α (after ε,ι,ρ)', 'Mixed α'],
    rows: [
      ['Nominative', '-α / -ια', '-α'],
      ['Genitive', '-ας / -ιας', '-ης'],
      ['Dative', '-ᾳ / -ιᾳ', '-ῃ'],
      ['Accusative', '-αν / -ιαν', '-αν'],
    ],
    examples: 'ἀλήθεια → ἀλήθεια, ἀληθείας, ἀληθείᾳ, ἀλήθειαν\nδόξα → δόξα, δόξης, δόξῃ, δόξαν',
  },
  {
    id: '2nd-masc',
    title: '2nd Declension (Masculine)',
    subtitle: 'Nouns like λόγος, θεός, κόσμος, νόμος',
    note: 'The 2nd declension is the backbone of Greek nouns. The omicron (ο) thematic vowel appears throughout. Key markers: -ος for nominative, -ου for genitive (this -ου is unique and unmistakable), -ῳ for dative (the iota subscript signals dative).',
    headers: ['', 'Singular', 'Plural'],
    rows: [
      ['Nominative', '-ος', '-οι'],
      ['Genitive', '-ου', '-ων'],
      ['Dative', '-ῳ', '-οις'],
      ['Accusative', '-ον', '-ους'],
    ],
    examples: 'λόγος → λόγος, λόγου, λόγῳ, λόγον / λόγοι, λόγων, λόγοις, λόγους',
  },
  {
    id: '2nd-neut',
    title: '2nd Declension (Neuter)',
    subtitle: 'Nouns like ἔργον, εὐαγγέλιον, τέκνον, ἱερόν',
    note: 'Neuter nouns follow one absolute rule: nominative and accusative forms are always identical. In the plural, neuter nom/acc always ends in -α. This is true across all declensions, not just the 2nd.',
    headers: ['', 'Singular', 'Plural'],
    rows: [
      ['Nominative', '-ον', '-α'],
      ['Genitive', '-ου', '-ων'],
      ['Dative', '-ῳ', '-οις'],
      ['Accusative', '-ον', '-α'],
    ],
    examples: 'ἔργον → ἔργον, ἔργου, ἔργῳ, ἔργον / ἔργα, ἔργων, ἔργοις, ἔργα',
  },
  {
    id: '3rd-consonant',
    title: '3rd Declension (Consonant Stems)',
    subtitle: 'Nouns like σάρξ (σαρκ-), χάρις (χαριτ-)',
    note: 'The 3rd declension has no single thematic vowel — the stem itself ends in a consonant. The key trick: find the genitive singular form, remove -ος, and you have the stem. All other forms build on that stem. Watch out: the gen sg -ος looks like 2nd decl nom sg -ος. Check the article!',
    headers: ['', 'Singular', 'Plural'],
    rows: [
      ['Nominative', '-ς or —', '-ες'],
      ['Genitive', '-ος', '-ων'],
      ['Dative', '-ι', '-σι(ν)'],
      ['Accusative', '-α or -ν', '-ας'],
    ],
    examples: 'σάρξ → σάρξ, σαρκός, σαρκί, σάρκα / σάρκες, σαρκῶν, σαρξί(ν), σάρκας',
  },
  {
    id: '3rd-mat',
    title: '3rd Declension (-ματ- stems)',
    subtitle: 'Nouns like πνεῦμα (πνευματ-)',
    note: 'All -μα nouns are neuter and follow the same pattern. The stem is -ματ-, visible in all forms except nom/acc singular where the τ drops. Since they are neuter, nom and acc are always identical.',
    headers: ['', 'Singular', 'Plural'],
    rows: [
      ['Nominative', '-μα', '-ματα'],
      ['Genitive', '-ματος', '-μάτων'],
      ['Dative', '-ματι', '-μασι(ν)'],
      ['Accusative', '-μα', '-ματα'],
    ],
    examples: 'πνεῦμα → πνεῦμα, πνεύματος, πνεύματι, πνεῦμα / πνεύματα, πνευμάτων, πνεύμασι(ν), πνεύματα',
  },
  {
    id: '3rd-irregular',
    title: '3rd Declension (Irregular)',
    subtitle: 'πατήρ, σωτήρ, βασιλεύς, αἰών',
    note: 'These nouns have stem changes between forms. πατήρ drops the ε in some forms (πατρός, not πατέρος). βασιλεύς has a υ/ε alternation. Learn these by exposure — the patterns become recognizable with practice.',
    headers: ['', 'πατήρ', 'βασιλεύς'],
    rows: [
      ['Nom sg', 'πατήρ', 'βασιλεύς'],
      ['Gen sg', 'πατρός', 'βασιλέως'],
      ['Dat sg', 'πατρί', 'βασιλεῖ'],
      ['Acc sg', 'πατέρα', 'βασιλέα'],
      ['Nom pl', 'πατέρες', 'βασιλεῖς'],
      ['Gen pl', 'πατέρων', 'βασιλέων'],
      ['Dat pl', 'πατράσι(ν)', 'βασιλεῦσι(ν)'],
      ['Acc pl', 'πατέρας', 'βασιλεῖς'],
    ],
    examples: '',
  },
];

export const VERB_PARADIGMS = [
  {
    id: 'pres-act-ind-omega',
    title: 'Present Active Indicative (ω-verbs)',
    subtitle: 'λύω pattern — the foundation of Greek verb conjugation',
    note: 'The present tense uses primary active endings attached to the present stem with the thematic vowel (ο/ε). These endings are the most common in the NT. The thematic vowel is ο before μ or ν, and ε elsewhere.',
    headers: ['Person', 'Singular', 'Plural'],
    rows: [
      ['1st', '-ω', '-ομεν'],
      ['2nd', '-εις', '-ετε'],
      ['3rd', '-ει', '-ουσι(ν)'],
    ],
    examples: 'πιστεύω, πιστεύεις, πιστεύει, πιστεύομεν, πιστεύετε, πιστεύουσιν',
  },
  {
    id: 'pres-act-ind-mi',
    title: 'Present Active Indicative (μι-verbs)',
    subtitle: 'δίδωμι, τίθημι pattern',
    note: 'μι-verbs attach endings directly to the stem without a thematic vowel. The stem vowel often lengthens in the singular and stays short in the plural. εἰμί (to be) is the most common μι-verb but is highly irregular.',
    headers: ['Person', 'Singular', 'Plural'],
    rows: [
      ['1st', '-μι', '-μεν'],
      ['2nd', '-ς', '-τε'],
      ['3rd', '-σι(ν)', '-ασι(ν)'],
    ],
    examples: 'δίδωμι, δίδως, δίδωσιν, δίδομεν, δίδοτε, διδόασιν\nεἰμί: εἰμί, εἶ, ἐστίν, ἐσμέν, ἐστέ, εἰσίν',
  },
  {
    id: 'pres-mid-pass-ind',
    title: 'Present Middle/Passive Indicative',
    subtitle: 'Same endings for both middle and passive',
    note: 'Middle and passive are identical in the present system. Context determines which is meant. The key marker is the -μαι/-σαι/-ται pattern. Deponent verbs (like γίνομαι, ἔρχομαι) use these endings but have active meaning.',
    headers: ['Person', 'Singular', 'Plural'],
    rows: [
      ['1st', '-ομαι', '-όμεθα'],
      ['2nd', '-ῃ (-εσαι)', '-εσθε'],
      ['3rd', '-εται', '-ονται'],
    ],
    examples: 'γίνομαι, γίνῃ, γίνεται, γινόμεθα, γίνεσθε, γίνονται',
  },
  {
    id: 'impf-act-ind',
    title: 'Imperfect Active Indicative',
    subtitle: 'Past continuous action',
    note: 'The imperfect adds an augment (ἐ-) to the beginning and uses secondary active endings. It only exists in the indicative mood. The augment signals past time; the present stem signals imperfective aspect (ongoing action).',
    headers: ['Person', 'Singular', 'Plural'],
    rows: [
      ['1st', 'ἐ- + stem + -ον', 'ἐ- + stem + -ομεν'],
      ['2nd', 'ἐ- + stem + -ες', 'ἐ- + stem + -ετε'],
      ['3rd', 'ἐ- + stem + -ε(ν)', 'ἐ- + stem + -ον'],
    ],
    examples: 'ἔλεγον, ἔλεγες, ἔλεγεν, ἐλέγομεν, ἐλέγετε, ἔλεγον\nNote: 1st sg and 3rd pl are identical (-ον)',
  },
  {
    id: 'aor-act-ind',
    title: 'Aorist Active Indicative',
    subtitle: 'Simple past action',
    note: 'First (sigmatic) aorist adds -σα- between stem and endings. Second aorist uses a different stem but present-tense-like endings. Both have the augment. The aorist is the most common past tense in narrative.',
    headers: ['', '1st Aorist', '2nd Aorist'],
    rows: [
      ['1st sg', 'ἐ- + stem + -σα', 'ἐ- + stem + -ον'],
      ['2nd sg', 'ἐ- + stem + -σας', 'ἐ- + stem + -ες'],
      ['3rd sg', 'ἐ- + stem + -σε(ν)', 'ἐ- + stem + -ε(ν)'],
      ['1st pl', 'ἐ- + stem + -σαμεν', 'ἐ- + stem + -ομεν'],
      ['2nd pl', 'ἐ- + stem + -σατε', 'ἐ- + stem + -ετε'],
      ['3rd pl', 'ἐ- + stem + -σαν', 'ἐ- + stem + -ον'],
    ],
    examples: '1st: ἐπίστευσα, ἐπίστευσας, ἐπίστευσεν...\n2nd: εἶπον, εἶπες, εἶπεν, εἴπομεν, εἴπετε, εἶπον',
  },
  {
    id: 'aor-mid-ind',
    title: 'Aorist Middle Indicative',
    subtitle: 'Past action in subject\'s interest',
    note: 'First aorist middle uses -σα- + middle endings. The aorist passive is different (uses -θη-) and is NOT the same as aorist middle. This is unlike the present system where middle and passive share forms.',
    headers: ['', '1st Aorist Middle'],
    rows: [
      ['1st sg', 'ἐ- + stem + -σάμην'],
      ['2nd sg', 'ἐ- + stem + -σω'],
      ['3rd sg', 'ἐ- + stem + -σατο'],
      ['1st pl', 'ἐ- + stem + -σάμεθα'],
      ['2nd pl', 'ἐ- + stem + -σασθε'],
      ['3rd pl', 'ἐ- + stem + -σαντο'],
    ],
    examples: 'ἀπεκρινάμην (I answered — from ἀποκρίνομαι)',
  },
  {
    id: 'fut-act-ind',
    title: 'Future Active/Middle Indicative',
    subtitle: 'Will do / will be doing',
    note: 'The future tense adds -σ- to the present stem, then uses primary active or middle endings — identical to the present tense endings. Think of it as present + σ. No augment (augment = past time, future = not past). Some verbs have irregular future stems (ἐρῶ from λέγω, ὄψομαι from ὁράω).',
    headers: ['Person', 'Active', 'Middle'],
    rows: [
      ['1st sg', '-σω', '-σομαι'],
      ['2nd sg', '-σεις', '-σῃ (-σεσαι)'],
      ['3rd sg', '-σει', '-σεται'],
      ['1st pl', '-σομεν', '-σόμεθα'],
      ['2nd pl', '-σετε', '-σεσθε'],
      ['3rd pl', '-σουσι(ν)', '-σονται'],
    ],
    examples: 'πιστεύσω (I will believe), πιστεύσεις, πιστεύσει...\nἐρῶ (I will say — irregular future of λέγω)',
  },
  {
    id: 'perf-act-ind',
    title: 'Perfect Active Indicative',
    subtitle: 'Completed action with ongoing results',
    note: 'The perfect uses reduplication (repeating the first consonant + ε) plus the -κα marker and special endings. It signals a completed action whose results continue into the present. "I have believed" = the believing happened and its effects persist. The most recognizable feature is the reduplication: πε-πίστευ-κα.',
    headers: ['Person', 'Singular', 'Plural'],
    rows: [
      ['1st', 'redupl. + stem + -κα', 'redupl. + stem + -καμεν'],
      ['2nd', 'redupl. + stem + -κας', 'redupl. + stem + -κατε'],
      ['3rd', 'redupl. + stem + -κε(ν)', 'redupl. + stem + -κασι(ν)'],
    ],
    examples: 'πεπίστευκα (I have believed)\nγέγραφα (I have written)\nεἴρηκα (I have said — from λέγω)',
  },
  {
    id: 'subjunctive',
    title: 'Subjunctive Mood',
    subtitle: 'Possibility, purpose, exhortation',
    note: 'The subjunctive lengthens the thematic vowel: ο→ω, ε→η. This is the single most reliable identifier. Subjunctive uses primary endings (like the present) but with these lengthened vowels. It appears most often with ἵνα (purpose), ἐάν (conditional), or as a hortatory subjunctive (1st person "let us...").',
    headers: ['Person', 'Active', 'Middle/Passive'],
    rows: [
      ['1st sg', '-ω', '-ωμαι'],
      ['2nd sg', '-ῃς', '-ῃ'],
      ['3rd sg', '-ῃ', '-ηται'],
      ['1st pl', '-ωμεν', '-ώμεθα'],
      ['2nd pl', '-ητε', '-ησθε'],
      ['3rd pl', '-ωσι(ν)', '-ωνται'],
    ],
    examples: 'ἵνα πιστεύωμεν (that we might believe)\nἐὰν εἴπωμεν (if we say)',
  },
  {
    id: 'imperative',
    title: 'Imperative Mood',
    subtitle: 'Commands and requests',
    note: 'The imperative has no 1st person (you can\'t command yourself — that\'s the hortatory subjunctive). The 2nd person forms are most common. Present imperative implies ongoing action ("keep doing X"); aorist imperative implies simple action ("do X").',
    headers: ['Person', 'Present Active', 'Aorist Active'],
    rows: [
      ['2nd sg', '-ε', '-σον (1st) / -ε (2nd)'],
      ['3rd sg', '-έτω', '-σάτω / -έτω'],
      ['2nd pl', '-ετε', '-σατε / -ετε'],
      ['3rd pl', '-έτωσαν', '-σάτωσαν / -έτωσαν'],
    ],
    examples: 'πίστευε (keep believing!) / πίστευσον (believe!)\nἔρχου (keep coming!) — present mid/pass 2sg imperative',
  },
  {
    id: 'participle-pres-act',
    title: 'Present Active Participle',
    subtitle: 'λύων, λύουσα, λῦον — "loosing" / "while loosing"',
    note: 'The present active participle uses -ντ- as its participial marker. Masculine and neuter follow 3rd declension patterns, while feminine follows 1st declension. The present stem signals ongoing/continuous action. This is the most common participle in the NT.',
    headers: ['', 'Masculine', 'Feminine', 'Neuter'],
    rows: [
      ['Nom sg', '-ων', '-ουσα', '-ον'],
      ['Gen sg', '-οντος', '-ούσης', '-οντος'],
      ['Dat sg', '-οντι', '-ούσῃ', '-οντι'],
      ['Acc sg', '-οντα', '-οῦσαν', '-ον'],
      ['Nom pl', '-οντες', '-οῦσαι', '-οντα'],
      ['Gen pl', '-όντων', '-ουσῶν', '-όντων'],
      ['Dat pl', '-οῦσι(ν)', '-ούσαις', '-οῦσι(ν)'],
      ['Acc pl', '-οντας', '-ούσας', '-οντα'],
    ],
    examples: 'λέγων, λέγουσα, λέγον (saying)\nπιστεύων, πιστεύουσα, πιστεῦον (believing)',
  },
  {
    id: 'participle-pres-mid-pass',
    title: 'Present Middle/Passive Participle',
    subtitle: 'λυόμενος, λυομένη, λυόμενον',
    note: 'The present middle/passive participle uses -μενος, -μένη, -μενον — standard 2nd/1st declension adjective endings. Identical for middle and passive; context determines which is meant. Very regular and easy to spot because of the -μεν- marker.',
    headers: ['', 'Masculine', 'Feminine', 'Neuter'],
    rows: [
      ['Nom sg', '-όμενος', '-ομένη', '-όμενον'],
      ['Gen sg', '-ομένου', '-ομένης', '-ομένου'],
      ['Dat sg', '-ομένῳ', '-ομένῃ', '-ομένῳ'],
      ['Acc sg', '-όμενον', '-ομένην', '-όμενον'],
      ['Nom pl', '-όμενοι', '-όμεναι', '-όμενα'],
      ['Gen pl', '-ομένων', '-ομένων', '-ομένων'],
      ['Dat pl', '-ομένοις', '-ομέναις', '-ομένοις'],
      ['Acc pl', '-ομένους', '-ομένας', '-όμενα'],
    ],
    examples: 'γινόμενος, γινομένη, γινόμενον (becoming)\nἐρχόμενος, ἐρχομένη, ἐρχόμενον (coming)',
  },
  {
    id: 'participle-aor-act',
    title: 'Aorist Active Participle',
    subtitle: '1st: λύσας, λύσασα, λῦσαν — 2nd: βαλών, βαλοῦσα, βαλόν',
    note: 'First aorist active participle uses -σαντ- marker (visible in oblique cases). Second aorist looks like present active but with the aorist stem. No augment — the augment only appears in the indicative. Aorist participle signals completed or simple action.',
    headers: ['', 'Masc (1st aor)', 'Fem (1st aor)', 'Neut (1st aor)'],
    rows: [
      ['Nom sg', '-σας', '-σασα', '-σαν'],
      ['Gen sg', '-σαντος', '-σάσης', '-σαντος'],
      ['Dat sg', '-σαντι', '-σάσῃ', '-σαντι'],
      ['Acc sg', '-σαντα', '-σᾶσαν', '-σαν'],
      ['Nom pl', '-σαντες', '-σᾶσαι', '-σαντα'],
      ['Gen pl', '-σάντων', '-σασῶν', '-σάντων'],
      ['Dat pl', '-σασι(ν)', '-σάσαις', '-σασι(ν)'],
      ['Acc pl', '-σαντας', '-σάσας', '-σαντα'],
    ],
    examples: 'πιστεύσας (having believed)\nλύσας, λύσασα, λῦσαν (having loosed)',
  },
  {
    id: 'participle-aor-pass',
    title: 'Aorist Passive Participle',
    subtitle: 'λυθείς, λυθεῖσα, λυθέν',
    note: 'The aorist passive participle uses the -θε- marker (from the aorist passive -θη-). It declines like a 3rd declension adjective in masc/neuter and 1st declension in feminine. The -θεντ- stem is visible in the oblique cases. Very recognizable once you spot -θείς/-θεῖσα/-θέν.',
    headers: ['', 'Masculine', 'Feminine', 'Neuter'],
    rows: [
      ['Nom sg', '-θείς', '-θεῖσα', '-θέν'],
      ['Gen sg', '-θέντος', '-θείσης', '-θέντος'],
      ['Dat sg', '-θέντι', '-θείσῃ', '-θέντι'],
      ['Acc sg', '-θέντα', '-θεῖσαν', '-θέν'],
      ['Nom pl', '-θέντες', '-θεῖσαι', '-θέντα'],
      ['Gen pl', '-θέντων', '-θεισῶν', '-θέντων'],
      ['Dat pl', '-θεῖσι(ν)', '-θείσαις', '-θεῖσι(ν)'],
      ['Acc pl', '-θέντας', '-θείσας', '-θέντα'],
    ],
    examples: 'βαπτισθείς (having been baptized)\nἐγερθείς (having been raised)',
  },
  {
    id: 'participle-perf-act',
    title: 'Perfect Active Participle',
    subtitle: 'λελυκώς, λελυκυῖα, λελυκός',
    note: 'The perfect active participle uses reduplication + the -κοτ-/-κυι- markers. It signals a completed action with ongoing results. Masculine/neuter are 3rd declension, feminine is 1st. Less common than present and aorist participles but important in narrative.',
    headers: ['', 'Masculine', 'Feminine', 'Neuter'],
    rows: [
      ['Nom sg', '-κώς', '-κυῖα', '-κός'],
      ['Gen sg', '-κότος', '-κυίας', '-κότος'],
      ['Dat sg', '-κότι', '-κυίᾳ', '-κότι'],
      ['Acc sg', '-κότα', '-κυῖαν', '-κός'],
      ['Nom pl', '-κότες', '-κυῖαι', '-κότα'],
      ['Gen pl', '-κότων', '-κυιῶν', '-κότων'],
      ['Dat pl', '-κόσι(ν)', '-κυίαις', '-κόσι(ν)'],
      ['Acc pl', '-κότας', '-κυίας', '-κότα'],
    ],
    examples: 'εἰδώς (knowing — from οἶδα)\nγεγραφώς (having written)',
  },
];

export const ARTICLE_PARADIGM = {
  id: 'article',
  title: 'The Definite Article',
  subtitle: 'ὁ, ἡ, τό — the most common word in the Greek NT',
  note: 'The article is your best friend for parsing. It always agrees with its noun in case, number, and gender, so if you can parse the article, you can parse the noun. The article has no vocative. Memorize this table completely — it unlocks noun parsing.',
  headers: ['', 'Masculine', 'Feminine', 'Neuter'],
  rows: [
    ['Nom sg', 'ὁ', 'ἡ', 'τό'],
    ['Gen sg', 'τοῦ', 'τῆς', 'τοῦ'],
    ['Dat sg', 'τῷ', 'τῇ', 'τῷ'],
    ['Acc sg', 'τόν', 'τήν', 'τό'],
    ['Nom pl', 'οἱ', 'αἱ', 'τά'],
    ['Gen pl', 'τῶν', 'τῶν', 'τῶν'],
    ['Dat pl', 'τοῖς', 'ταῖς', 'τοῖς'],
    ['Acc pl', 'τούς', 'τάς', 'τά'],
  ],
  examples: 'ὁ λόγος (the word, nom) / τοῦ λόγου (of the word, gen) / τῷ λόγῳ (to the word, dat)\nἡ ζωή (the life, nom) / τό ἔργον (the work, nom)',
};
